### ISSUE TITLE
When changing the attribute type, the template is not changed in rendersetting.

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_translatedtext#15]
When changing the attribute type, the template is not changed in rendersetting.

e.g. change from translatedtext to text, the call to the template of translatedtext is retained

**Comment by discordier** [comment]
First off, the changing of the type of an attribute is still to be considered experimental.

I fail to see how to determine which template to use when changing and even in which rendersettings as you might have changed it to a custom template on purpose.

When you did not use a custom template (leaving the selection empty) it should work though.

**Comment by zonky2** [comment]
A custom template was not used. You can fix it by deleting the attribute from the render settings and adding a new one.

**Comment by zonky2** [comment]
moved to https://github.com/MetaModels/core/issues/1435
