### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/attribute_translatedtext#9]
## Checklist before I submit this issue report

I confirm that:
- [ ] I have tested this with the latest version available
- [ ] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_translatedtext/issues?q=is%3Aissue

## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |    -      |                                  |
| Contao version:                     |     -     |                                  |
| MetaModels version:                 |     -     |                                  |
| Installation via composer           | - |                                  |
| Installed MetaModels packages       |     -     |                                  |

## Issue description
We should add the regex. 
## Steps to reproduce
Go into the DCA Settings for the attribute.
## Describe the behaviour of the application

https://github.com/MetaModels/attribute_translatedtext/blob/master/contao/dca/tl_metamodel_dcasetting.php#L41

## Describe the expected behaviour of the application

https://github.com/MetaModels/attribute_text/blob/master/contao/dca/tl_metamodel_dcasetting.php#L39

**Comment by zonky2** [comment]
@stefanheimes make you a PR?

**Comment by zonky2** [comment]
@stefanheimes pls check PR https://github.com/MetaModels/attribute_translatedtext/pull/10

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?

**Comment by zonky2** [comment]
Issue is´t ready

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@stefanheimes could you please have a final look at this and tell if your issue has been resolved?

**Comment by zonky2** [comment]
@stefanheimes Deine Freundin MiniModel benötigt einen Kosmetiktermin!

**Comment by zonky2** [comment]
@stefanheimes und nochmal: bitte PR prüfen...

**Comment by zonky2** [comment]
fixed in https://github.com/MetaModels/attribute_translatedtext/pull/10
